export const products = [
  {
    id: "1",
    slug: "premium-wireless-headphones",
    title: "Premium Wireless Headphones",
    description:
      "Experience crystal-clear sound with our premium wireless headphones featuring noise cancellation and 30-hour battery life.",
    categoryId: 1,
    basePrice: 299.99,
    offerPrice: 249.99,
    stock: 50,
    color: "Black",
    variantName: "Color",
    variantValues: "Black, White, Blue",
    shortDescription: "Noise-cancelling wireless headphones",
    keywords: ["headphones", "wireless", "audio", "music"],
    purchases: 120,
    earnings: 29998.8,
    rating: 4.5,
    reviews: 42,
    featured: true,
    wishlisted: true,
    images: [
      "/products/headphones-1.jpg",
      "/products/headphones-2.jpg",
      "/products/headphones-3.jpg",
    ],
    specs: {
      brand: "AudioMaster",
      connectivity: "Bluetooth 5.0",
      batteryLife: "30 hours",
      noiseCancellation: true,
      weight: "250g",
    },
  },
  {
    id: "3",
    slug: "premium-wireless-headphones",
    title: "Premium Wireless Headphones",
    description:
      "Experience crystal-clear sound with our premium wireless headphones featuring noise cancellation and 30-hour battery life.",
    categoryId: 1,
    basePrice: 299.99,
    offerPrice: 249.99,
    stock: 50,
    color: "Black",
    variantName: "Color",
    variantValues: "Black, White, Blue",
    shortDescription: "Noise-cancelling wireless headphones",
    keywords: ["headphones", "wireless", "audio", "music"],
    purchases: 120,
    earnings: 29998.8,
    rating: 4.5,
    reviews: 42,
    featured: true,
    wishlisted: true,
    images: [
      "/products/headphones-1.jpg",
      "/products/headphones-2.jpg",
      "/products/headphones-3.jpg",
    ],
    specs: {
      brand: "AudioMaster",
      connectivity: "Bluetooth 5.0",
      batteryLife: "30 hours",
      noiseCancellation: true,
      weight: "250g",
    },
  },
  {
    id: "2",
    slug: "ultra-hd-smart-tv",
    title: "Ultra HD Smart TV",
    description:
      "65-inch 4K Ultra HD Smart TV with HDR and built-in streaming apps for the ultimate home entertainment experience.",
    categoryId: 2,
    basePrice: 1299.99,
    offerPrice: 1099.99,
    stock: 25,
    color: "Black",
    variantName: "Size",
    variantValues: "55-inch, 65-inch, 75-inch",
    shortDescription: "65-inch 4K Ultra HD Smart TV",
    keywords: ["tv", "television", "4k", "smart"],
    purchases: 78,
    earnings: 85799.22,
    rating: 4.8,
    reviews: 56,
    featured: true,
    wishlisted: false,
    images: ["/products/tv-1.jpg", "/products/tv-2.jpg", "/products/tv-3.jpg"],
    specs: {
      brand: "VisionPlus",
      screenSize: "65-inch",
      resolution: "3840 x 2160",
      refreshRate: "120Hz",
      smartFeatures: true,
    },
  },
  {
    id: "4",
    slug: "premium-wireless-headphones",
    title: "Premium Wireless Headphones",
    description:
      "Experience crystal-clear sound with our premium wireless headphones featuring noise cancellation and 30-hour battery life.",
    categoryId: 1,
    basePrice: 299.99,
    offerPrice: 249.99,
    stock: 50,
    color: "Black",
    variantName: "Color",
    variantValues: "Black, White, Blue",
    shortDescription: "Noise-cancelling wireless headphones",
    keywords: ["headphones", "wireless", "audio", "music"],
    purchases: 120,
    earnings: 29998.8,
    rating: 4.5,
    reviews: 42,
    featured: true,
    wishlisted: true,
    images: [
      "/products/headphones-1.jpg",
      "/products/headphones-2.jpg",
      "/products/headphones-3.jpg",
    ],
    specs: {
      brand: "AudioMaster",
      connectivity: "Bluetooth 5.0",
      batteryLife: "30 hours",
      noiseCancellation: true,
      weight: "250g",
    },
  },
  {
    id: "5",
    slug: "premium-wireless-headphones",
    title: "Premium Wireless Headphones",
    description:
      "Experience crystal-clear sound with our premium wireless headphones featuring noise cancellation and 30-hour battery life.",
    categoryId: 1,
    basePrice: 299.99,
    offerPrice: 249.99,
    stock: 50,
    color: "Black",
    variantName: "Color",
    variantValues: "Black, White, Blue",
    shortDescription: "Noise-cancelling wireless headphones",
    keywords: ["headphones", "wireless", "audio", "music"],
    purchases: 120,
    earnings: 29998.8,
    rating: 4.5,
    reviews: 42,
    featured: true,
    wishlisted: true,
    images: [
      "/products/headphones-1.jpg",
      "/products/headphones-2.jpg",
      "/products/headphones-3.jpg",
    ],
    specs: {
      brand: "AudioMaster",
      connectivity: "Bluetooth 5.0",
      batteryLife: "30 hours",
      noiseCancellation: true,
      weight: "250g",
    },
  },
  {
    id: "6",
    slug: "premium-wireless-headphones",
    title: "Premium Wireless Headphones",
    description:
      "Experience crystal-clear sound with our premium wireless headphones featuring noise cancellation and 30-hour battery life.",
    categoryId: 1,
    basePrice: 299.99,
    offerPrice: 249.99,
    stock: 50,
    color: "Black",
    variantName: "Color",
    variantValues: "Black, White, Blue",
    shortDescription: "Noise-cancelling wireless headphones",
    keywords: ["headphones", "wireless", "audio", "music"],
    purchases: 120,
    earnings: 29998.8,
    rating: 4.5,
    reviews: 42,
    featured: true,
    wishlisted: true,
    images: [
      "/products/headphones-1.jpg",
      "/products/headphones-2.jpg",
      "/products/headphones-3.jpg",
    ],
    specs: {
      brand: "AudioMaster",
      connectivity: "Bluetooth 5.0",
      batteryLife: "30 hours",
      noiseCancellation: true,
      weight: "250g",
    },
  },
  {
    id: "7",
    slug: "premium-wireless-headphones",
    title: "Premium Wireless Headphones",
    description:
      "Experience crystal-clear sound with our premium wireless headphones featuring noise cancellation and 30-hour battery life.",
    categoryId: 1,
    basePrice: 299.99,
    offerPrice: 249.99,
    stock: 50,
    color: "Black",
    variantName: "Color",
    variantValues: "Black, White, Blue",
    shortDescription: "Noise-cancelling wireless headphones",
    keywords: ["headphones", "wireless", "audio", "music"],
    purchases: 120,
    earnings: 29998.8,
    rating: 4.5,
    reviews: 42,
    featured: true,
    wishlisted: true,
    images: [
      "/products/headphones-1.jpg",
      "/products/headphones-2.jpg",
      "/products/headphones-3.jpg",
    ],
    specs: {
      brand: "AudioMaster",
      connectivity: "Bluetooth 5.0",
      batteryLife: "30 hours",
      noiseCancellation: true,
      weight: "250g",
    },
  },
  {
    id: "8",
    slug: "premium-wireless-headphones",
    title: "Premium Wireless Headphones",
    description:
      "Experience crystal-clear sound with our premium wireless headphones featuring noise cancellation and 30-hour battery life.",
    categoryId: 1,
    basePrice: 299.99,
    offerPrice: 249.99,
    stock: 50,
    color: "Black",
    variantName: "Color",
    variantValues: "Black, White, Blue",
    shortDescription: "Noise-cancelling wireless headphones",
    keywords: ["headphones", "wireless", "audio", "music"],
    purchases: 120,
    earnings: 29998.8,
    rating: 4.5,
    reviews: 42,
    featured: true,
    wishlisted: true,
    images: [
      "/products/headphones-1.jpg",
      "/products/headphones-2.jpg",
      "/products/headphones-3.jpg",
    ],
    specs: {
      brand: "AudioMaster",
      connectivity: "Bluetooth 5.0",
      batteryLife: "30 hours",
      noiseCancellation: true,
      weight: "250g",
    },
  },
  {
    id: "9",
    slug: "premium-wireless-headphones",
    title: "Premium Wireless Headphones",
    description:
      "Experience crystal-clear sound with our premium wireless headphones featuring noise cancellation and 30-hour battery life.",
    categoryId: 1,
    basePrice: 299.99,
    offerPrice: 249.99,
    stock: 50,
    color: "Black",
    variantName: "Color",
    variantValues: "Black, White, Blue",
    shortDescription: "Noise-cancelling wireless headphones",
    keywords: ["headphones", "wireless", "audio", "music"],
    purchases: 120,
    earnings: 29998.8,
    rating: 4.5,
    reviews: 42,
    featured: true,
    wishlisted: true,
    images: [
      "/products/headphones-1.jpg",
      "/products/headphones-2.jpg",
      "/products/headphones-3.jpg",
    ],
    specs: {
      brand: "AudioMaster",
      connectivity: "Bluetooth 5.0",
      batteryLife: "30 hours",
      noiseCancellation: true,
      weight: "250g",
    },
  },
  {
    id: "10",
    slug: "premium-wireless-headphones",
    title: "Premium Wireless Headphones",
    description:
      "Experience crystal-clear sound with our premium wireless headphones featuring noise cancellation and 30-hour battery life.",
    categoryId: 1,
    basePrice: 299.99,
    offerPrice: 249.99,
    stock: 50,
    color: "Black",
    variantName: "Color",
    variantValues: "Black, White, Blue",
    shortDescription: "Noise-cancelling wireless headphones",
    keywords: ["headphones", "wireless", "audio", "music"],
    purchases: 120,
    earnings: 29998.8,
    rating: 4.5,
    reviews: 42,
    featured: true,
    wishlisted: true,
    images: [
      "/products/headphones-1.jpg",
      "/products/headphones-2.jpg",
      "/products/headphones-3.jpg",
    ],
    specs: {
      brand: "AudioMaster",
      connectivity: "Bluetooth 5.0",
      batteryLife: "30 hours",
      noiseCancellation: true,
      weight: "250g",
    },
  },
  {
    id: "11",
    slug: "premium-wireless-headphones",
    title: "Premium Wireless Headphones",
    description:
      "Experience crystal-clear sound with our premium wireless headphones featuring noise cancellation and 30-hour battery life.",
    categoryId: 1,
    basePrice: 299.99,
    offerPrice: 249.99,
    stock: 50,
    color: "Black",
    variantName: "Color",
    variantValues: "Black, White, Blue",
    shortDescription: "Noise-cancelling wireless headphones",
    keywords: ["headphones", "wireless", "audio", "music"],
    purchases: 120,
    earnings: 29998.8,
    rating: 4.5,
    reviews: 42,
    featured: true,
    wishlisted: true,
    images: [
      "/products/headphones-1.jpg",
      "/products/headphones-2.jpg",
      "/products/headphones-3.jpg",
    ],
    specs: {
      brand: "AudioMaster",
      connectivity: "Bluetooth 5.0",
      batteryLife: "30 hours",
      noiseCancellation: true,
      weight: "250g",
    },
  },
  // Add more products as needed
];
